---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: openpolicyagent/demo-test-server:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-service
spec:
  type: ClusterIP
  selector:
    app: example-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app-cert
  namespace: default
spec:
  secretName: example-app-cert
  subject:
    organizations:
    - snakeoil
  dnsNames:
  - localhost
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example-app-proxy
spec:
  virtualhost:
    fqdn: localhost
    tls:
      secretName: example-app-cert
    # Note that ext_authz only works when TLS is enabled
    # with contour.
    authorization:
      extensionRef:
        name: opa-extsvc
        namespace: projectcontour
  routes:
  - conditions:
    - prefix: /
    # For testing purposes
    permitInsecure: true
    services:
      - name: example-app-service
        port: 8080
