apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-crt
spec:
  secretName: self-signed-root
  commonName: "self-signed-root"
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
